<a href="https://colab.research.google.com/github/paulocesardev8/descomplica-faculdade/blob/main/atividade_pratica_descomplica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Este arquivo Python utiliza a biblioteca NumPy para realizar diversas operações com arrays e matrizes, incluindo a criação, acesso a elementos, fatiamento, operações matemáticas, cálculo de soma e média, transposição e concatenação.

import numpy as np

# 2. Crie um array unidimensional chamado arr com os números de 1 a 10.
arr = np.arange(1, 11)

# 3. Crie uma matriz bidimensional chamada matriz com dimensões 3x4, preenchida com números inteiros de 1 a 12.
matriz = np.arange(1, 13).reshape(3, 4)

# 4. Imprima o array arr e a matriz matriz.
print("Array arr:", arr)
print("Matriz matriz:\n", matriz)

# 5. Acesse o elemento “5” do array arr e o elemento “8” da matriz matriz. Imprima os valores obtidos.
elemento_arr = arr[4]  # O índice 4 é o quinto elemento
elemento_matriz = matriz[1, 3]  # Segunda linha, quarta coluna (índices começam em 0)
print("Elemento 5 do array arr:", elemento_arr)
print("Elemento 8 da matriz matriz:", elemento_matriz)

# 6. Crie um novo array chamado arr_slice que contenha os elementos do array arr no intervalo de índices de 2 a 6 (exclusivo).
arr_slice = arr[2:6]
print("Array arr_slice:", arr_slice)

# 7. Realize uma operação matemática de sua escolha (por exemplo, multiplicação por 2) em todos os elementos do array arr e armazene o resultado em um novo array chamado arr_resultado.
arr_resultado = arr * 2
print("Array arr_resultado:", arr_resultado)

# 8. Calcule a soma de todos os elementos da matriz matriz. Imprima o valor obtido.
soma_matriz = np.sum(matriz)
print("Soma de todos os elementos da matriz matriz:", soma_matriz)

# 9. Calcule a média dos elementos do array arr e imprima o valor obtido.
media_arr = np.mean(arr)
print("Média dos elementos do array arr:", media_arr)

# 10. Crie uma matriz chamada matriz_transposta que seja a transposta da matriz matriz. Imprima a matriz matriz_transposta.
matriz_transposta = np.transpose(matriz)
print("Matriz matriz_transposta:\n", matriz_transposta)

# 11. Concatene o array arr com o array arr_slice e armazene o resultado em um novo array chamado arr_concatenado. Imprima o array arr_concatenado.
arr_concatenado = np.concatenate((arr, arr_slice))
print("Array arr_concatenado:", arr_concatenado)


Array arr: [ 1  2  3  4  5  6  7  8  9 10]
Matriz matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elemento 5 do array arr: 5
Elemento 8 da matriz matriz: 8
Array arr_slice: [3 4 5 6]
Array arr_resultado: [ 2  4  6  8 10 12 14 16 18 20]
Soma de todos os elementos da matriz matriz: 78
Média dos elementos do array arr: 5.5
Matriz matriz_transposta:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Array arr_concatenado: [ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]
