<a href="https://colab.research.google.com/github/paulocesardev8/descomplica-faculdade/blob/main/Atividade_pratica%2C_descomplica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Array arr:", arr)
print("Matriz matriz:")
print(matriz)

elemento_arr = arr[4]  # Índice 4, valor 5
elemento_matriz = matriz[1, 3]  # Linha 1, Coluna 3, valor 8
print("Elemento 5 do array arr:", elemento_arr)
print("Elemento 8 da matriz matriz:", elemento_matriz)

arr_slice = arr[2:6]
print("Array arr_slice:", arr_slice)

arr_resultado = arr * 2
print("Array arr_resultado (arr multiplicado por 2):", arr_resultado)

soma_matriz = np.sum(matriz)
print("Soma de todos os elementos da matriz matriz:", soma_matriz)


media_arr = np.mean(arr)
print("Média dos elementos do array arr:", media_arr)

matriz_transposta = matriz.T
print("Matriz transposta:")
print(matriz_transposta)

arr_concatenado = np.concatenate((arr, arr_slice))
print("Array concatenado (arr + arr_slice):", arr_concatenado)

Array arr: [ 1  2  3  4  5  6  7  8  9 10]
Matriz matriz:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elemento 5 do array arr: 5
Elemento 8 da matriz matriz: 8
Array arr_slice: [3 4 5 6]
Array arr_resultado (arr multiplicado por 2): [ 2  4  6  8 10 12 14 16 18 20]
Soma de todos os elementos da matriz matriz: 78
Média dos elementos do array arr: 5.5
Matriz transposta:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Array concatenado (arr + arr_slice): [ 1  2  3  4  5  6  7  8  9 10  3  4  5  6]
